# https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: comcon-import-api-prod
  labels:
    app: comcon-import-api-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comcon-import-api-prod
  template:
    metadata:
      labels:
        app: comcon-import-api-prod
    spec:
      volumes:
        - name: bot-config
          secret:
            secretName: comcon-api-secret-prod

      containers:
        - image: gcr.io/sym-bizops-bots/comcon-api-prod:1.0
          name: comcon-api
          env:
            - name: DEPLOY_TYPE
              value: prod
          volumeMounts:
            - name: bot-config
              mountPath: "/etc/comcon_import/config"
              readOnly: true